import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";

import { Montserrat } from "next/font/google"

const montserratFont = Montserrat({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${montserratFont.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
